version: "3.9"

services:
  db:
    image: postgres:18
    container_name: taskmanager_db
    environment:
#      POSTGRES_USER: <...>
#      POSTGRES_PASSWORD: <...>
      POSTGRES_DB: task_manager
    ports:
#      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data